const ProjectsInfo = {
    project0: {
        id:"",
        nombre: "",
        name: "",
        contenido: "",
        content: "",
        link: "",
        githubLink: "",
        imagen: "",
    },
    project1: {
        id:"Project1",
        nombre: "DriveIn",
        name: "DriveIn",
        contenido: "Una concesionaria localizada en las ciudades turisticas mas visitadas de latinoamerica donde tu puedes rentar el vehiculo que mas te guste de nuetro catalogo. Este sitio web fue creado como grupo en un periodo de 4 semanas, con sprints cada semana.",
        content: "A concessionary located in the most visited tourist cities in Latin America where you can rent the vehicle you like from our catalog. This website was created as a group in a period of 4 weeks, with a sprint each week.",
        link: "https://drivein.vercel.app/",
        githubLink: "https://github.com/Naotari/DriveIn",
        imagen: "https://res.cloudinary.com/dyiymsxec/image/upload/v1674577847/Portfolio/Projects/DriveIn.png",
    },
    project2: {
        id:"Project2",
        nombre: "Razas de Perros",
        name: "Dog Breeds",
        contenido: "Un catalogo de razas de perros donde puedes encontrar todas las razas existentes, ademas puedes añadir tu perro a la coleccion. Esta fue mi primera pagina web creada.",
        content: "A catalog of dog breeds where you can find all breeds existence, also you can add your dog to the collection. This was my first web created.",
        link: "https://dog-breeds-naotari.vercel.app/",
        githubLink: "https://github.com/Naotari/Dog-Breeds",
        imagen: "https://res.cloudinary.com/dyiymsxec/image/upload/v1674578526/Portfolio/Projects/DogBreeds.png",
    },
    project3: {
        id:"Project3",
        nombre: "portafolio V1",
        name: "Portfolio V1",
        contenido: "Esta es la pagina que diseñe para mostrar toda la informacion acerca de mi y los proyectos que he hecho.",
        content: "This is the web I desiged to show all information about me and the projects I made.",
        link: "https://portfolio-naotari.vercel.app/",
        githubLink: "https://github.com/Naotari/Portfolio",
        imagen: "https://res.cloudinary.com/dyiymsxec/image/upload/v1674591580/Portfolio/Projects/Portfolio.png",
    },
    project4: {
        id:"Project4",
        nombre: "Calculadora",
        name: "Calculator",
        contenido: "Esta es una calculadora basica creada para practicar conceptos basicos de javascript.",
        content: "This is a basic calculator created to practice basic concepts in javascript.",
        link: "https://calculator-naotari.vercel.app/",
        githubLink: "https://github.com/Naotari/calculator",
        imagen: "https://res.cloudinary.com/dyiymsxec/image/upload/v1708817535/Portfolio/Projects/Calculator.png",
    },
    project5: {
        id:"Project5",
        nombre: "Portafolio V2",
        name: "Portfolio V2",
        contenido: "La segunda version de mi portafolio para enseñar los proyectos en los cuales trabaje y estoy trabajando.",
        content: "Second version of my portfolio to showcase the projects I have worked on and am currently working on.",
        link: "https://frandelrodriguez.vercel.app/",
        githubLink: "https://github.com/Naotari/PortfolioV2",
        imagen: "https://res.cloudinary.com/dyiymsxec/image/upload/v1708812496/Portfolio/Projects/Portfolio%20V2.png",
    },
    project6: {
        id:"Project6",
        nombre: "AdoptaGT",
        name: "AdoptaGT",
        contenido: "Estamos desarrollando esta plataforma con el propósito de establecer una red de adopciones en Guatemala, facilitando así que un mayor número de animales encuentren un hogar adecuado.",
        content: "We are developing this platform with the purpose of establishing an adoption network in Guatemala, making it easier for a greater number of animals to find a suitable home.",
        link: "https://adoptagt.vercel.app/",
        githubLink: "https://github.com/Naotari/AdoptaGT-client",
        imagen: "https://res.cloudinary.com/dyiymsxec/image/upload/v1708812725/Portfolio/Projects/AdoptaGT.png",
    },
}
export default ProjectsInfo